version: '3.3'
services:
  app:
    build: .
    container_name: php-fpm
    volumes:
      - ./:/app

  clickhouse:
    image: yandex/clickhouse-server
    container_name: clickhouse
    ports:
      - "8123:8123"
##      - "9000:9000"
##      - "9009:9009"
#    ulimits:
#       nproc: 65535
#       nofile:
#         soft: 262144
#         hard: 262144
#  clickouse_client:
#    image: yandex/clickhouse-client
#    container_name: clickhouse-client
#    command: ['--host', 'server']