version: '3.3'
services:
  app:
    build: .
    container_name: php-fpm
    volumes:
      - ./:/app

  clickhouse:
    image: yandex/clickhouse-server
    container_name: clickhouse
    ports:
      - "8123:8123"